In [1]:
#Import all packages
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import sklearn
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error

In [2]:
#Load the data set into Pandas
df = pd.read_csv('churn_prepared.csv', index_col = 0)
df.describe()

,Children,Income,Outage_sec_perweek,Yearly_equip_failure,Tenure,MonthlyCharge,Bandwidth_GB_Year,Churn_num,Techie_num,Port_modem_num,...,Phone_num,Multiple_num,OnlineSecurity_num,OnlineBackup_num,DeviceProtection_num,TechSupport_num,StreamingTV_num,StreamingMovies_num,Contract_num,InternetService_num
count,10000.0000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2.0877,39806.926771,10.001848,0.398000,34.526188,172.624816,3392.341550,0.265000,0.167900,0.483400,...,0.906700,0.460800,0.357600,0.450600,0.438600,0.375000,0.492900,0.489000,0.698600,1.227900
std,2.1472,28199.916702,2.976019,0.635953,26.443063,42.943094,2185.294852,0.441355,0.373796,0.499749,...,0.290867,0.498486,0.479317,0.497579,0.496241,0.484147,0.499975,0.499904,0.836079,0.775772
min,0.0000,348.670000,0.099747,0.000000,1.000259,79.978860,155.506715,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0000,19224.717500,8.018214,0.000000,7.917694,139.979239,1236.470827,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,1.0000,33170.605000,10.018560,0.000000,35.430507,167.484700,3279.536903,0.000000,0.000000,0.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,3.0000,53246.170000,11.969485,1.000000,61.479795,200.734725,5586.141370,1.000000,0.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
max,10.0000,258900.700000,21.207230,6.000000,71.999280,290.160419,7158.981530,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,2.000000

In [3]:
#Set up for train - test split
X = df.drop('MonthlyCharge', axis = 1).values
y = df['MonthlyCharge'].values

In [4]:
#Split the data set with an 80/20 split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, test_size = 0.2, random_state = 25)

In [5]:
#Save the training and testing sets as csv files
pd.DataFrame(X_train).to_csv('X_train.csv')
pd.DataFrame(X_test).to_csv('X_test.csv')
pd.DataFrame(y_train).to_csv('y_train.csv')
pd.DataFrame(y_test).to_csv('y_test.csv')

In [6]:
#Run gridsearch cv to find best max depth and leaves[1][2]
dt = DecisionTreeRegressor()
param_grid = {"max_depth": range(1, 8),
              "min_samples_leaf": range(1, 5)}
grid = GridSearchCV(dt, param_grid, cv = 5)
grid.fit(X_train, y_train)
print('The best parameters for this model: {}'.format(grid.best_params_))

The best parameters for this model: {'max_depth': 7, 'min_samples_leaf': 1}

In [7]:
#Fit the decision tree model with the found parameters
dt = DecisionTreeRegressor(max_depth = 7, min_samples_leaf = 1)
dt.fit(X_train, y_train)

y_pred = dt.predict(X_test)

In [8]:
mse_dt = mean_squared_error(y_test, y_pred)
rmse_dt = mse_dt**(1/2)

print("Accuracy: ", dt.score(X_test, y_test))
print("Mean squared error: ", mse_dt)
print("Root mean squared error: ", rmse_dt)

Accuracy:  0.9878364202122181
Mean squared error:  22.58501693453698
Root mean squared error:  4.752369612576128